/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniverseRouteImport } from './routes/universe'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChartingRouteImport } from './routes/charting'
import { Route as IndexRouteImport } from './routes/index'

const UniverseRoute = UniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartingRoute = ChartingRouteImport.update({
  id: '/charting',
  path: '/charting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charting': typeof ChartingRoute
  '/dashboard': typeof DashboardRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/positions': typeof PositionsRoute
  '/trades': typeof TradesRoute
  '/universe': typeof UniverseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charting': typeof ChartingRoute
  '/dashboard': typeof DashboardRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/positions': typeof PositionsRoute
  '/trades': typeof TradesRoute
  '/universe': typeof UniverseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charting': typeof ChartingRoute
  '/dashboard': typeof DashboardRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/positions': typeof PositionsRoute
  '/trades': typeof TradesRoute
  '/universe': typeof UniverseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/charting'
    | '/dashboard'
    | '/logs'
    | '/metrics'
    | '/positions'
    | '/trades'
    | '/universe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charting'
    | '/dashboard'
    | '/logs'
    | '/metrics'
    | '/positions'
    | '/trades'
    | '/universe'
  id:
    | '__root__'
    | '/'
    | '/charting'
    | '/dashboard'
    | '/logs'
    | '/metrics'
    | '/positions'
    | '/trades'
    | '/universe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChartingRoute: typeof ChartingRoute
  DashboardRoute: typeof DashboardRoute
  LogsRoute: typeof LogsRoute
  MetricsRoute: typeof MetricsRoute
  PositionsRoute: typeof PositionsRoute
  TradesRoute: typeof TradesRoute
  UniverseRoute: typeof UniverseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universe': {
      id: '/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof UniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charting': {
      id: '/charting'
      path: '/charting'
      fullPath: '/charting'
      preLoaderRoute: typeof ChartingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChartingRoute: ChartingRoute,
  DashboardRoute: DashboardRoute,
  LogsRoute: LogsRoute,
  MetricsRoute: MetricsRoute,
  PositionsRoute: PositionsRoute,
  TradesRoute: TradesRoute,
  UniverseRoute: UniverseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
